### ISSUE TITLE
[NullGuard] Out parameter 'value' is null

### ISSUE THREAD

**Issue by papuashu** [Fody/NullGuard#46]
I have a simple method like this:
public bool TryGetValue(TKey key, [AllowNull] out TValue value)
but upon exiting from it I get the above error when "value" parameter is assigned a null value.

Is it a bug in NullGuard or am I using it wrong?

**Comment by distantcam** [comment]
That appears to be a missed scenario. I'll try to add that soon.

**Comment by MovGP0** [comment]
There are multiple ways to go around this issue. One way is to disable the checks of Out-paremters on the class level. 
```csharp
[NullGuard(ValidationFlags.Properties | ValidationFlags.Arguments | ValidationFlags.ReturnValues | ValidationFlags.NonPublic)]
public sealed class MyClass
{
    ...
}
```

Another way is to introduce a Maybe-Monad. A simple version might look something like:  

```csharp
public interface Maybe<T>{}
 
public class None<T> : Maybe<T>
{
    public override string ToString()
    {
        return string.Empty;
    }
}
 
public class Some<T> : Maybe<T>
{
    public T Value { get; private set; }
 
    public Some(T value)
    {
        Value = value;
    }
 
    public override string ToString()
    {
        return Value.ToString();
    }
}
```
Reference: [Wikipedia: LINQ](https://de.wikipedia.org/wiki/LINQ#Maybe)

So instead of returning ```null```, you would return an instance of ```None```. This is also very useful to implement ```null``` propagation - especially when you are not using C# 6.0.

**Comment by distantcam** [comment]
This has been added to 1.4.1
