### ISSUE TITLE
Null checks in constructors are being injected before the base() call

### ISSUE THREAD

**Issue by shana** [Fody/NullGuard#51]
It looks like constructors are getting null checks injected before any base() calls get to happen. This is not correct, base() calls are meant to be the first thing that happens, so that the base class constructor is the first one to be called and executed before any code runs on child class constructors(guaranteeing the integrity of the allocated memory for the object). This is the only time where it's "safe" to call base methods on a constructor, and no exceptions should be thrown before this happens.

**Comment by ulrichb** [comment]
@shana 
I don't agree that the current behavior is incorrect. NullGuard behaves the same way as manually checking the arguments with a static method in the base call:

```C#
public TheInheritor(TheArgument theArgument)
    : base(Preconditions.CheckNotNull(theArgument).Id) { }
```

See this [Stack Overflow answer from Jon Skeet](http://stackoverflow.com/a/4803427/50890).

Changing this behavior would no longer allow to safely access properties in the base call (like the `.Id` access in the example).

**Comment by shana** [comment]
@ulrichb 
That's not the same use case as a general one where you forward arguments to the base class, or when there is no base() call (in which case the compiler inserts a base call to the Object .ctor). If a base call uses arguments that were passed to the constructor, then yes, I agree, checks should be injected for those arguments, to emulate the code you posted.

Anything else should only be validated after the base call is done, because that's the order in which things are supposed to happen - the base call is the very first thing that happens, nothing else should occur before it, to guarantee the integrity of the object. It's not safe to run any other code until the Object constructor has been called and everything fully allocated for the instance (even if it's just to abort it right after), and even though it's rare that it will leave the runtime in a bad state, there is the potential for it.

**Comment by Haacked** [comment]
> I don't agree that the current behavior is incorrect. NullGuard behaves the same way as manually checking the arguments with a static method in the base call:

This is not how I'd expect `NullGuard` to behave. I'd expect it to behave like so:

```csharp
public TheInheritor(TheArgument theArgument) : base(theArgument) {
}
```

Gets transformed to...

```csharp
public TheInheritor(TheArgument theArgument) : base(theArgument) {
    if (theArgument == null) thow new ArgumentNullException(...);
}
```

The reason is that the base class should validate its own arguments. An `ArgumentNullException` implies it's being thrown by method receiving the bad argument.

**Comment by Haacked** [comment]
Also, if the base class doesn't validate the arguments (maybe it's a protected ctor or a 3rd party base class), then that might actually be the expected behavior that the base ctor succeeds before we validate arguments on the `TheInheritor`. Problem is, neither behavior can be unilaterally stated to be the "correct" behavior in all cases.

**Comment by distantcam** [comment]
There's nothing I can find in the ECMA spec to say that you must call the base ctor before anything else. In fact sometimes the base ctor is never called, for example with structs.

The only thing I could find that was relevant was CLS Rule 21 which says "An object constructor shall call some class constructor of its base class before any access occurs to inherited instance data. This does not apply to value types, which need not have constructors."

I'm inclined to allow this fix as it follows what the compiler would do in the situation where the null guard was manually added as the first thing in the body of the constructor.

However, there's currently a bug in the PR. Consider the following code.

    public struct TheStruct
    {
        public TheStruct(int i)
        {
            Item = new object();
        }

        public object Item;
    }

	.method public hidebysig specialname rtspecialname 
		instance void .ctor (
			int32 i
		) cil managed 
	{
		// Method begins at RVA 0x2050
		// Code size 13 (0xd)
		.maxstack 8

		IL_0000: nop
		IL_0001: ldarg.0
		IL_0002: newobj instance void [mscorlib]System.Object::.ctor()
		IL_0007: stfld object MSILCheck.TheStruct::Item
		IL_000c: ret
	} // end of method TheStruct::.ctor

Because structs don't have a base there's no call to a base constructor. The PR would instead pick up the call to the object initialization and place the guard after that, which in this case is between the object creation and it's assignment to the field, which is obviously wrong.

**Comment by distantcam** [comment]
Ah nevermind. I realized the new call uses `newobj` and the base call uses `call` op codes.

I really mustn't respond to technical things after midnight.

**Comment by ulrichb** [comment]
@Haacked 
I agree that this behavior is a bit surprising when seeing it the first time and should be documented well. But is the less surprising behavior worth trading it with manual checks for property accesses, I described above, when NullGuard's mission is to reduce these checks? In which situation is the current behavior really a problem?

> The reason is that the base class should validate its own arguments. An ArgumentNullException implies it's being thrown by method receiving the bad argument.
> Also, if the base class doesn't validate the arguments (maybe it's a protected ctor or a 3rd party base class), then that might actually be the expected behavior that the base ctor succeeds before we validate arguments on the TheInheritor. Problem is, neither behavior can be unilaterally stated to be the "correct" behavior in all cases.

Is it semantically wrong when the outer c'tor already throws before passing the null value? This is the same behavior as in method chains. If the base c'tor allows null values, the derived c'tor would throw an ArgNullException later anyways, and therefore the object instance *will be* disposed/not used (except when the base c'tor leaks an alias of `this` which is an anti-pattern). => Follows fail fast principle.

**Comment by Haacked** [comment]
@shana is the current behavior causing any real problems for us?

**Comment by shana** [comment]
@ulrichb 
> Is it semantically wrong when the outer c'tor already throws before passing the null value (as it's the case in "normal" method chains)? If the base c'tor allows null values, the derived c'tor would throw an ArgNullException later anyways, and therefore the object instance will be disposed/unusable (except when the base c'tor leaks an alias of this which is an anti-pattern). => Follows fail fast principle.

Actually, it is not known if the base constructor throws the same exception. The base constructor might be in another library that doesn't use NullGuard and throws different types of exceptions in this case. It might do logging or other operations in case of a null argument before throwing. As it stands right now, the base class will have no chance of handling this situation because the null checks are being injected too early in the process.

Undocumented runtime behaviour and other things that might or might not go boom aside, for me the main issue is: NullGuard is here to automate calls that I would have to write manually otherwise. I don't see any reason why it would add these calls in a different place than what the compiler would if I wrote them manually. Doing it as close to what the compiler does is imo the best way of guaranteeing that nothing breaks in any runtime where this could possibly run (and I've spent enough time on Mono to know that breaking compiler assumptions doesn't lead down good roads). It also guarantees that it won't break the assumptions that people have about where things are being checked.

>`public TheInheritor(TheArgument theArgument)
    : base(Preconditions.CheckNotNull(theArgument).Id) { }`

I've updated the PR to fix this case. It will inject null checks for arguments that are actually used in a this/base call - by accessing properties or fields, or by calling methods that use the argument.
All other arguments, including the ones that are forwarded to another constructor, will get null checks added after the ctor call.

This allows base classes to properly handle arguments that they own as they see fit, and if they don't, the child class handles them afterwards. Code like the one pasted above will trigger a null check to happen for that argument before the ctor call so it, and everyone will be happy :smile:

**Comment by shana** [comment]
@distantcam 
Yeah, the newobj vs call is such a handy distinction, makes the detection code really simple. :smile:

In a completely unrelated thing, it looks like the 2015 compiler (or the disassembler, not sure yet) is generating different .line markers, which is annoying because it triggers a bunch of false-positive error noise during test runs. The extra il I added to the approved files is probably slightly different that what you'd get with VS 2013 or earlier because of that. Are you using the line information for anything specific? If not, then taking them out will help reduce compatibility issues between compilers in the test runs.

**Comment by distantcam** [comment]
@shana Yeah 2015 is using the new Roslyn compiler which I imagine is producing subtly different code to the old compiler.

The line info is so the debugger steps over the guards as you debug methods. Otherwise the debugger complains that it's running code it cannot find the source for.

**Comment by shana** [comment]
@distantcam 

> Yeah 2015 is using the new Roslyn compiler which I imagine is producing subtly different code to the old compiler.

Mostly it looks pretty much the same, except for the yield. Oh boy does that look different...

> The line info is so the debugger steps over the guards as you debug methods. Otherwise the debugger complains that it's running code it cannot find the source for.

Right. But is it needed for the approved tests where the decompiler output is compared against a master file? Anything that gets added changes line numbers, and it looks like Roslyn is adding line numbers in places where it didn't before, so it ends up being that the only thing different in most diffs is the line number. I'm not sure how useful the line information is in this case.

**Comment by ulrichb** [comment]
@shana If you extend your PR by detecting the pre base call parameter member accesses, we got the best of both worlds, and I'm indeed happy. The only thing I'm not sure about is if the additional complexity is worth it.

**Comment by shana** [comment]
@ulrichb As per my comments above, the PR is already updated with that logic. The complexity overhead is pretty negligible, a couple of extra conditions and a lookahead of maybe 4 or 6 instructions, if that.

**Comment by fschmied** [comment]
@shana, @distantcam Just want to add my opinion that, as a longish-time user of NullGuard that also has some experience with code generation, I've never had an issue with the null checks occurring before the base call. This is absolutely allowed by the runtime specification (ECMA-335), verifier, and CLR implementation. It's most probably also allowed by the Mono implementation (or are there known problems with the current implementation?). The C# compiler uses this not only for expressions (including static calls) on parameters, but also for field initializers. Code generators I've worked on, such Castle DynamicProxy, re-mix, and TypePipe, have also made use of this feature from time to time when it seemed useful. (Disclaimer: I have no idea if any of these projects _currently_ generate code executed prior to the base call.)

Therefore I'm quite confident that NullGuard can continue making use of this feature if deemed sensible. Of course, if there are any real issues with this on Mono, .NET Core, or something else, the issue is perfectly valid. Otherwise, I don't think one should make a change like this driven by fear of potential runtime bugs.

I can agree with the argument "NullGuard should write the same code as I would", but when I write the code manually, I have different options:
1. pass the argument unchecked to the base ctor, do not check afterwards,
2. pass it unchecked to the base ctor, check afterwards,
3. check it first, then pass it to the base ctor,
4. check it, don't pass it to the base ctor (but pass something else).

With NullGuard, I cannot make this choice, I automatically get one of these options:
- always check before calling the base ctor: inconsistent with what I'd write manually, very simple implementation;
- always check after the base ctor: sometimes inconsistent with what I'd write manually, fails @ulrichb's example, very simple implementation;
- check before the base ctor if parameter is used in an expression, otherwise check after the base ctor: often (but not always) consistent with what I'd write manually (see the three choices in manual code above), complex implementation.

Before choosing the most complex option, I'd think twice if the current implementation really has an issue that _needs to be fixed_,

**Comment by shana** [comment]
> Before choosing the most complex option, I'd think twice if the current implementation really has an issue that needs to be fixed

@fschmied As I mentioned before, it's not only potential runtime problems that are driving this issue. The behaviour currently doesn't allow base classes to handle the arguments they own in any way, because the child class will throw before it ever gets to that point, regardless of whether it's an argument that the child class actually uses (forwarding arguments is a common situation). To allow the base class to handle arguments properly, I would have to mark AllowNull on the child class for those arguments. But that's not correct, they shouldn't be null, so then I have to "lie" to be able to let the base class validate things.

If it's a base class that I don't control, I don't know what type of validation it's doing, so I can't duplicate that validation properly. The only thing I can do is choose between not validating the argument at all automatically, by marking it AllowNull and doing a manual null check (which kinda misses the while point of nullguard :smile:), or letting NullGuard check it, in which case whatever behaviour the base class had to validate it is now lost. Neither of these options is good. PR #52 fixes this behaviour, and as a bonus, it places null checks in the same place where the compiler would put them if I coded them manually.

TBH, the change is really not that complex, it's a few extra checks in a single method...

**Comment by ulrichb** [comment]
@shana 
You argued a few times that it's a problem that at the moment a base class can't handle null argument values. But IMO you gave no real reason *why* this is a problem. As, due to the `ArgNullException` in the derived class, the instance *will* be later disposed anyways (assuming `this` is not aliased), the only reason could be side-effects in the base c'tor, like your mentioned logging side-effects. But immediate logging (instead of later logging the `ArgNullException`) of `null` argument values in a base c'tor? Rly?

For me the only reason to change the behavior is that it would generate the same IL as writing manual if-then checks. *But:* As we have an exemption, isn't the rule "c'tor null checks happen *before* the base call" easier to document/understand as "c'tor parameter null check happens *after* the base call, *except* there is a member access for the parameter"?

When you see NullGuard not as a tool that adds (otherwise manually written) null-checks, but as a tool that adds **implicit (design by contract) preconditons for null values**, it becomes easier to see that it's OK that c'tor arguments are checked immediately, so that the rest of the c'tor code (including the base call) can **rely on these preconditions**.

**Comment by shana** [comment]
@ulrichb 

> You argued a few times that it's a problem that at the moment a base class can't handle null argument values. But IMO you gave no real reason why this is a problem.

I explained exactly why this is a problem in the following comment:

> Actually, it is not known if the base constructor throws the same exception. The base constructor might be in another library that doesn't use NullGuard and throws different types of exceptions in this case. It might do logging or other operations in case of a null argument before throwing. As it stands right now, the base class will have no chance of handling this situation because the null checks are being injected too early in the process.

I've fixed the PR so that any member accesses to constructor arguments trigger null checks before they occur (fixing your earlier example of SomeClass.Id being passed in the base call). All the null checks are made before any constructor code runs, and this change allows base classes to handle and throw if they want to without being bypassed by child classes, which is something that right now you can't do with NullGuard (subclassing classes that come from libraries that don't use NullGuard is pretty common, and they do have their own ways of validating arguments, but I still want to keep null values from being passed into constructors). I'm not sure what the problem is.

**Comment by distantcam** [comment]
@shana 
To be clear, there is nowhere in any documentation that says that the base call must be done first in the constructor. The Roslyn compiler will put field initializers before the base call in the constructor, which means the CLR can support this. If Mono doesn't support this then that's a bug in Mono and not our problem.

So the current implementation is valid.

So the argument becomes should NullGuard do what you'd be able to write in C# code, or fail fast by injecting code you cannot write manually in C#.

The change is small, but it is non-trivial and as we've discovered in this issue there might be edge cases where it would break.

**Comment by shana** [comment]
@distantcam

> The change is small, but it is non-trivial and as we've discovered in this issue there might be edge cases where it would break.

I pushed fixes for the edge case that was mentioned here as soon as it was raised, four days ago :-P

**Comment by shana** [comment]
@distantcam

> So the argument becomes should NullGuard do what you'd be able to write in C# code, or fail fast by injecting code you cannot write manually in C#.

That's not the only argument. The current behaviour of NullGuard makes it impossible for base classes to run validations before child classes. Just because I use nullguard and wish to fail fast doesn't mean the base class I'm subclassing also uses it - it might want to clear static state before throwing, it might want to log or other things. NullGuard currently breaks this scenario.

**Comment by fschmied** [comment]
@shana

> That's not the only argument. The current behaviour of NullGuard makes it impossible for base classes to run validations before child classes.

Can't this argument equally well be turned around after merging your pull request? With the proposed change, I could no longer validate arguments _before_ passing them to the base class (e.g., to suppress any side effects the base class could have):

    public class Derived : Base
    {
        public Derived (string message)
         : base (ArgumentUtility.IsNotNull("message", message)) // Should be automatically performed by NullGuard
        {
        }
    }

I recently worked on a code base where this pattern was extremely common. With regard to that code base, NullGuard's current behavior was perfect, whereas your PR would break the scenario. I'm not saying that the current behavior is better (maybe the scenario you're enabling is more common, maybe not). Just that it's not immediately obvious that the current behavior is broken or wrong.

> TBH, the change is really not that complex, it's a few extra checks in a single method...

Complexity is relative, of course. Some might find the lines starting from https://github.com/Fody/NullGuard/pull/52/files#diff-03524e28d003aca7f52e43317e00bb80R103 complex to understand, others might not. I personally find it hard to reason whether they are correct and complete.

For example, I think the code in the PR doesn't detect if a parameter passed to a base constructor is used in an array access expression. Therefore, the following snippet would cause a `NullReferenceException` if `null` was passed for the array parameter:

    class Derived : Base
    {
        public Derived (int[] nullCheckedByFody)
          : base (nullCheckedByFody[0])
        {
        }
      }

It also doesn't handle unboxing conversions of nullable value types or loading of virtual function pointers:

    class Derived : Base
    {
        public Derived (int? nullCheckedByFody1, string nullCheckedByFody2)
          : base ((int) nullCheckedByFody1, (Func<string>) nullCheckedByFody2.ToString)
        {
        }
      }

Is it okay that these cause `NullReferenceExceptions`? Maybe yes, maybe no. The need to contemplate and answer this kind of questions is the complexity I mean.

(By the way, if NullGuard needs this feature, it's not a problem that it has some inherent complexity. I just wanted to point out that it isn't just a few checks. It's also a few choices and a few potential bugs :) )

**Comment by ulrichb** [comment]
@fschmied 
Good catch, these are missing rules for the detection of dereferenciation of arguments which make it even more complex. And I don't just mean implementation complexity but also complexity of the specification / documentation of the (exemption) rule for c'tors, see my earlier https://github.com/Fody/NullGuard/issues/51#issuecomment-108524698.


@shana 
> I explained exactly why this is a problem in the following comment:
> 
>     Actually, it is not known if the base constructor throws the same exception. The base constructor might be in another library that doesn't use NullGuard and throws different types of exceptions in this case. It might do logging or other operations in case of a null argument before throwing. As it stands right now, the base class will have no chance of handling this situation because the null checks are being injected too early in the process.

Regarding "different type of exception in base class": Can you provide an example in which cases a base class should throw a different exception than an `ArgumentNullException` in this specific case?

Regarding side-effects in base class (you mentioned logging and resetting static members): Also here I would be interested in real world examples. Further, as in these cases `null` values have an *externally visible effect* (we have not *just preconditions*), I think the parameter can be declared as `[AllowNull]`, and therefore documented, anyways (in base and derived classes).

**Comment by distantcam** [comment]
People have had enough time to comment on this. I'll be closing this now without merge.

Reasons to not merge:
- Current behaviour is supported by C# and CLR.
- This would change current behaviour, which existing users may be relying on.
- It's a non-trivial amount of code to support.

I'm happy to revisit this if someone can demonstrate a bug on their system caused by this, but for now I'm going to close.
