### ISSUE TITLE
Does not work with Fody 2.0.4

### ISSUE THREAD

**Issue by Caleb9** [Fody/NullGuard#72]
Trying to build a project containing references to NullGuard.Fody 1.4.6 and Fody 2.0.4 results in an error:
`Fody: The weaver assembly 'NullGuard.Fody, Version=1.4.6.0, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll (cecilReference.Version). At least version 0.10 is expected. The weaver needs to add a NuGet reference to FodyCecil version 2.0.4.0.`

**Comment by roman-polunin-medamerica** [comment]
Also trying to do the similar logic in my own variant of NullGuard with Fody 2.0.6, completely messes up debugging information. This is because Cecil's Instruction no longer has .SequencePoint property. Sequence points now reference instructions by offset, and seems like Fody does not save my newly generated SequencePoints to disk.

**Comment by distantcam** [comment]
Please try 1.5.1
